import * as React from "react"

import Layout from "../components/layout"

const PolicyPage = () => {
  return (
    <Layout>
      <section className="privacy-canvas">
        <div className="container">
          <div className="intro-wrapper">
            <h2 className="intro-title">Privacy Policy</h2>
          </div>
          <hr className="my-5" />
          <p>
            Hanshow Technology Co. Ltd and its affiliates (collectively,
            &ldquo;Hanshow&rdquo;, &ldquo;us&rdquo;, &ldquo;we&rdquo; and
            &ldquo;our&rdquo;) respect your privacy and take the security of
            your Personal Data very seriously. We have always solemnly promised
            to protect the privacy of Users (the &ldquo;User&rdquo; or
            &ldquo;you&rdquo;) of our website www.hanshow.com (the
            &ldquo;Website&ldquo;) and will ensure that the Personal Data
            collected on this Website is only used as described in this Privacy
            Policy.
          </p>
          <p>
            Our Privacy Policy explains how we collect, use, share and protect
            information in relation to our Website. We collect this information
            when you visit our Website with your computer, tablet or mobile
            phone (&ldquo;Device&rdquo;). To the extent Personal Data of an EU
            Data Subject is Processed or the Processing is performed within the
            EU, we Process Personal Data in a manner that is in accordance with
            the General Data Protection Regulation (the &ldquo;GDPR&rdquo;), the
            GDPR-based legislation and all other relevant laws and regulations
            which currently are in effect. To the extent applicable, all
            capitalized terms in this Privacy Policy have the same meaning as
            defined in the GDPR.
          </p>
          <h6 className="mt-5">Section 1: Data Controller</h6>
          <p>
            Hanshow is the Data Controller for the Processing of Personal Data
            in the following situations:
          </p>
          <ul>
            <li>
              the Processing of Personal Data in the context of the customer
              relationship with Hanshow or potential customers with whom Hanshow
              has made contact or wishes to make contact;
            </li>
            <li>
              the Processing of Personal Data of Users of our Website and all
              underlying and/or linked websites and/or website pages;
            </li>
            <li>
              the Processing of Personal Data of recipients of promotions,
              newsletters and commercial emails from Hanshow;
            </li>
            <li>
              the Processing of all other Personal Data relating to persons who
              contact Hanshow or whose Personal Data Hanshow Processes.
            </li>
          </ul>
          <h6 className="mt-5">Section 2: Source of Data</h6>
          <p>
            Personal Data means any information that, either on its own or
            jointly with other information, can be used to identify a natural
            person. Hanshow Processes Personal Data that you have provided to
            Hanshow yourself and Personal Data generated during your visit to
            the Website. This includes contact details and information about
            assignments, such as (company) name, address, telephone number,
            email address and other Personal Data that you voluntarily provide
            to us when you contact us or communicate with us. Personal Data
            obtained through or generated by our Website includes information
            about your IP address, internet browser, language settings, and
            information about your use of our Websites. We collect this data by
            placing cookies.
          </p>
          <p>
            We may also collect and use non-personally identifiable information
            (Non-PII). Non-PII is information that cannot be used to identify a
            particular individual. For example, Hanshow will collect statistical
            data, such as the numbers, source, location of visits to the
            Website. We collect this data to understand how Users use our
            Websites and services so that we can improve our services and better
            satisfy your needs. Hanshow may collect, use, process, transfer, or
            disclose non-PII for other purposes at its own discretion.
          </p>
          <h6 className="mt-5">Section 3: Personal Data of minors</h6>
          <p>
            Our Website and/or services are not aimed at persons under the age
            of 18 and do not intend to collect (Personal) Data from and about
            Users who are younger than 18 years of age. However, we cannot check
            whether a User is older than 18 years. If you are under the age of
            18 and it appears that our services are offered to you, you may only
            use them under the supervision and with the permission of your legal
            representative. If you or your legal representative are convinced
            that we have collected your (Personal) Data without your/its
            permission, you or your legal representative can contact us via the
            email address provided in Section 14 below. We will then delete your
            Personal Data as soon as possible.
          </p>
          <h6 className="mt-5">Section 4: Cookies and Similar Technologies</h6>
          <p>
            A Cookie is a piece of information in the form of a very small text
            file that is placed on an internet user's hard drive. It is
            generated by a web page server, which is basically the computer that
            operates a website. The information the Cookie contains is set by
            the server and it can be used by that server whenever the user
            visits the website. A Cookie can be thought of as an internet user's
            identification card, which tell a website when the user has
            returned.
          </p>
          <p>
            Cookies make the interaction between users and websites faster and
            easier. Without Cookies, it would be very difficult for a website to
            remember the user's preferences for a future visit. Websites use
            Cookies mainly because they save time and make the browsing
            experience more efficient and enjoyable. Websites often use Cookies
            for the purposes of collecting demographic information about their
            users.
          </p>
          <p>
            Like many other websites or Internet service providers, Hanshow uses
            Cookies to improve User experience and perform activities necessary
            for our operations, for instance, web traffic analysis. We use
            Cookies to save browsing preferences and to optimize the User's
            browsing experience. Among these Cookies are, for example, those
            used for the setting of language. Hanshow will not use Cookies for
            any purposes not stated in this Privacy Policy.
          </p>
          <p>
            We understand that you as an Internet user may have reservations
            about cookies. To avoid misconceptions, we would like to clarify
            with you following points:
          </p>
          <ul>
            <li>Cookies cannot transmit viruses</li>
            <li>Cookies cannot read e-mail addresses</li>
            <li>Cookies cannot read disk contents</li>
            <li>Cookies cannot transmit the history file</li>
            <li>Cookies cannot send unnoticed e-mails</li>
            <li>
              Cookies cannot write all over your hard disk or even delete it
            </li>
          </ul>
          <p>
            Necessary Cookies and similar technologies are essential to enable
            the core functionality of the website, which cannot be disabled via
            the function of this site. You can generally reject or manage
            Cookies and similar technologies through the browser or User
            selection mechanism. For details, visit e.g. AboutCookies.org.
            However, please note that if you disable Cookies or similar
            technologies, we may not be able to provide you with the best
            service experience, and some services may not work properly.
          </p>
          <h6 className="mt-5">Section 5: Purposes</h6>
          <p>Hanshow uses your Personal Data for various purposes, such as:</p>
          <ul>
            <li>
              the execution of an agreement between you and Hanshow, for which
              you have commissioned Hanshow to provide our products and /or
              services;
            </li>
            <li>compliance with legal obligations;</li>
            <li>maintaining contact with you;</li>
            <li>sending you information you have requested from us;</li>
            <li>improving our product and /or service information;</li>
            <li>creating user statistics of the Website.</li>
          </ul>
          <h6 className="mt-5">
            Section 6: Legal basis for the Processing of Personal Data of EU
            Data Subjects
          </h6>
          <p>
            In regard to the Processing of Personal Data of EU Data Subjects or
            when the Personal Data is Processed within the EU, Hanshow will
            Process your Personal Data following the requirements of applicable
            laws on an appropriate legal basis. Hanshow Processes your Personal
            Data exclusively on the basis of one of the following principles:
          </p>
          <ul>
            <li>
              Consent. If we have asked you for your Consent to Process your
              Personal Data and you have given this Consent, you also have the
              right to withdraw this Consent at any time;
            </li>
            <li>
              Execution of the Agreement. If you commission us to provide you
              with our products and/or services, we Process Personal Data if and
              insofar as this is necessary for the execution of the assignment;
            </li>
            <li>
              Legal Obligation. In some cases we are legally bind to Process
              your Personal Data, e.g. for tax obligations;
            </li>
            <li>
              Legitimate Interest. This includes our interest in maintaining a
              (commercial) relationship with you and our commercial interest in
              gaining more insight into the use of our Website.
            </li>
          </ul>
          <h6 className="mt-5">Section 7: Retention period</h6>
          <p>
            Hanshow does not store Personal Data that it Processes for longer
            than is necessary for the purpose of the Processing or required by
            law. The retention period may differ per type of Personal Data.
          </p>
          <p>
            Personal Data Processed for purposes related to the execution of an
            agreement between you and Hanshow shall be retained until such
            agreement has been fully performed. Personal Data Processed for the
            purposes of legitimate interests shall be retained as long as needed
            to fulfill such purposes.
          </p>
          <p>
            Personal Data that we obtain via our Website (other than through
            Cookies) is stored for a maximum of two (2) weeks, after which it is
            removed from our system. We may use Cookies that can place and read
            data on your Device. These Cookies are stored for the duration as
            describe in Section 4 above, or at most until the Cookie is deleted
            by you.
          </p>
          <p>
            We may anonymize Personal Data for statistical purposes and store it
            on an aggregated level. There is no maximum retention period
            attached to such.
          </p>
          <h6 className="mt-5">Section 8: Third Parties and Processors</h6>
          <p>
            We may disclose your Personal Data to Hanshow affiliates or a third
            party authorized to cooperate. We may need to provide certain
            services to you through some partners. In order to do so, we may
            need to share some of your Personal Data with our partners. In
            addition, as a global company, we may share Personal Data within the
            Hanshow companies.
          </p>
          <p>
            To comply with applicable laws or respond to valid legal procedures,
            Hanshow may also disclose your Personal Data to law enforcement or
            other government agencies. If Hanshow is involved in a
            restructuring, merger &amp; acquisition, or a bankruptcy or
            liquidation lawsuit in a given jurisdiction, your Personal Data may
            be disclosed in connection with the transaction. Hanshow may also
            disclose your Personal Data when appropriate, for example, to
            execute Terms and Conditions, when we believe disclosure is
            necessary or appropriate to prevent physical harm or financial loss,
            or when it is in connection with an investigation of suspected or
            actual illegal activity.
          </p>
          <p>
            For the Processing of Personal Data, Hanshow engages service
            providers (Processors) who Process the Personal Data on behalf of
            Hanshow. Hanshow concludes a Processing Agreement with these
            Processors that, regarding the Processing of Personal Data of EU
            Data Subjects and/or Processing of Personal Data within the EU,
            meets the requirements of the GDPR. For example, Hanshow works with
            ICT service providers and service providers that offer software or
            hosting services. Furthermore, there are also ICT service providers
            who offer us support in keeping our systems safe and stable.
          </p>
          <h6 className="mt-5">Section 9: International Transfer</h6>
          <p>
            The principle is that your Personal Data is processed at our
            operating offices and in any other place where the parties involved
            in the Processing are located. Depending on your location, data
            transfers may involve transferring your Personal Data to a country
            other than their own.
          </p>
          <p>
            As a global company, generally, we will Process your Personal Data
            in the country/region where you visit our Website. However, your
            Personal Data may be Processed or accessed in the country/region
            where you use our products and services or in other
            countries/regions where Hanshow or its affiliates, subsidiaries,
            service providers or business partners have a presence. These
            jurisdictions may have different information protection laws. In
            such circumstances, Hanshow will take measures to ensure that
            information is processed as required by this Privacy Policy and
            applicable laws.
          </p>
          <h6 className="mt-5">
            Section 10: Your rights as an EU Data subject
          </h6>
          <p>
            As an EU Data Subject or when your Personal Data is Processed within
            the EU, you have a number of rights under the GDPR. You have the
            right to access your Personal Data (Art. 15 GDPR), the right to
            rectification of your Personal Data (Art. 16 GDPR), the right to
            erasure (Art. 17 GDPR) and the right to restriction of Processing
            (Art. 18 GDPR). Under certain circumstances, you also have the right
            to request the transfer of your Personal Data (Art. 20 GDPR).
            Finally, you can object to the use of your Personal Data (Art. 21
            GDPR). If the Processing of your Personal Data is based on Consent,
            you can withdraw it at any time.
          </p>
          <p>Your rights are briefly described below:</p>
          <ul>
            <li>
              <strong>right of access:</strong> you may always request an
              overview of the Personal Data we have collected and request a copy
              thereof. If we have received your Personal Data not directly from
              you but from a third party who Processes your Personal Data, we
              will inform you of the source from which this information was
              received;
            </li>
            <li>
              <strong>right to rectification:</strong> you may always ask for
              your Personal Data to be corrected or supplemented if they have
              been Processed incorrectly and/or incompletely in our
              administration;
            </li>
            <li>
              <strong>right to erasure:</strong> you may always request that
              your Personal Data be deleted if you do not want us to retain
              certain Personal Data about you. This is also called 'the right to
              be forgotten';
            </li>
            <li>
              <strong>right to restriction:</strong> you can always ask for the
              Processing of your Personal Data to be temporarily stopped or for
              the use thereof to be restricted;
            </li>
            <li>
              <strong>right to transfer:</strong> you can always request your
              Personal Data to be transferred to a third party. This is also
              called the right to data portability. Your Personal Data will then
              be sent to you or to the third party designated by you in a
              readable file;
            </li>
            <li>
              <strong>right to object:</strong> you can (under certain
              circumstances) object to the (further) Processing of your Personal
              Data; and
            </li>
            <li>
              <strong>withdraw your Consent at any time:</strong> you have the
              right to withdraw your Consent where you have previously given
              your Consent to the Processing of your Personal Data. However,
              withdrawal does not affect the legitimacy and effectiveness of how
              we Process your Personal Data based on your Consent before the
              withdrawal is made; nor does it affect any Personal Data
              Processing based on another legal basis/justification other than
              your Consent.
            </li>
          </ul>
          <p>
            When you claim the said rights, we may require you to submit a
            written request and may verify your identify. Usually, we do not
            charge anything for such processes unless your request goes beyond
            the limit of conventional requirements.
          </p>
          <h6 className="mt-5">Section 11: Security</h6>
          <p>
            We have taken reasonable and practical measures and technical
            measures to protect your Personal Data we Process. Please note,
            however, that although we have taken reasonable steps to protect
            your Personal Data, no website, Internet transmission, computer
            system or wireless connection is absolutely safe and without
            defects. Hanshow ensures appropriate security of the Personal Data
            it holds, in accordance with the applicable requirements and
            guidelines. The measures we have taken include:
          </p>
          <ul>
            <li>
              that all data via the Website is encrypted and transmitted via a
              secure connection by means of SSL/TLS connections;
            </li>
            <li>
              that only the necessary persons have access to personal data, that
              access to the data is protected and that our security measures are
              regularly checked;
            </li>
            <li>
              that persons who have access to data are aware of the importance
              we attach to the protection of personal data;
            </li>
            <li>
              that persons who have access to data are bound by a
              confidentiality agreement.
            </li>
          </ul>
          <p>
            If you have the impression that your Personal Data is not properly
            secured or there are indications of a Data Breach, please contact us
            immediately.
          </p>
          <h6 className="mt-5">
            Section 12: Obligation to report Data Breaches regarding EU Data
            Subjects
          </h6>
          <p>
            Despite the fact that we Process your Personal Data with the utmost
            care and your Personal Data are stored securely, it is possible that
            a Data Breach occurs. Should such Data Breach occur in regard to
            Personal Data of an EU Data Subject or the Processing of Personal
            Data with the EU, we will first check whether and to what extent
            there may be a high risk to your rights and freedoms. In such a
            case, we will report this to the relevant DPA within seventy-two
            (72) hours and we will also report this to you as soon as possible.
          </p>
          <p>
            In the event of a Data Breach, we will notify you at least of the
            following:
          </p>
          <ul>
            <li>the type of breach related to your personal data;</li>
            <li>the likely consequences of the infringement;</li>
            <li>
              the measures to be taken (and already taken) by us to limit the
              consequences of the infringement.
            </li>
          </ul>
          <h6 className="mt-5">Section 13: Alterations</h6>
          <p>
            We reserve the right to update or make changes to this Privacy
            Policy at any time. Therefore, please regularly consult this Privacy
            Policy for an update. We will release the latest Privacy Policy on
            our Website for any changes. You agree to visit the Website
            regularly to check any such revisions. If there is any major change
            to this Privacy Policy, we will notify you of such change by notable
            means, for example, the mean of pop-ups. The current version of this
            Privacy Policy was last modified on{" "}
            <strong>23 November 2021</strong>.
          </p>
          <h6 className="mt-5">Section 14: Questions or Complaints?</h6>
          <p>
            If you have any questions or complaints about the use of your
            Personal Data or about our Privacy Policy, please contact us via{" "}
            <span className="text-decoration-underline">
              dataprotection@hanshow.com
            </span>
            . We will do our utmost best to reply as soon as possible.
          </p>
          <p>
            You also have the right to complain to your national / regional data
            protection authority or the data protection commissioner.
          </p>
        </div>
      </section>
    </Layout>
  )
}

export default PolicyPage
